name: Release to GHCR

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  retag-push-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # needed to update the release body
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Retag latest as release version (multi-arch safe)
        run: |
          IMAGE=$(echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          VERSION=${{ github.ref_name }}

          echo "Creating multi-arch tag $IMAGE:$VERSION from $IMAGE:latest"
          docker buildx imagetools create -t $IMAGE:$VERSION $IMAGE:latest
